# Project Information
site_name: 'Joshua Yorko - Resume'
site_description: 'Site Reliability Engineer'
site_author: 'Joshua Yorko'
site_url: 'https://joshyorko.github.io'
repo_url: 'https://github.com/joshyorko/yorko-resume'
repo_name: 'yorko-resume'
edit_uri: ''

# Navigation Configuration
nav:
  - Home: 'index.md'

# Theme Configuration
theme:
  name: 'material'
  logo: 'assets/images/logo.png' 
  favicon: 'assets/images/favicon.ico'
  
  features:
    - navigation.tabs
    - navigation.instant

  palette:
    scheme: 'slate'  # Enforces dark mode
    primary: 'indigo'
    accent: 'indigo'

  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  
# Plugin Configuration
plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago

# Markdown Extensions
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - nl2br
  - sane_lists
  - smarty
