[tool.poetry]
name = "yorko-resume"
version = "0.1.0"
description = ""
authors = ["jyorko <joshua.yorko@gmail.com.com>"]
readme = "README.md"
package-mode = false

[project]
name = "yorko-resume"
version = "0.1.0"
description = "Resume site built with MkDocs Material"
authors = [ {name = "Joshua Yorko", email = "joshua.yorko@gmail.com"} ]
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
	"mkdocs==1.5.3",
	"mkdocs-material==9.4.6",
	"mkdocs-minify-plugin==0.7.1",
	"mkdocs-git-revision-date-localized-plugin==1.2.1",
	"mkdocs-glightbox==0.3.4",
	"pymdown-extensions==10.8"
]

[tool.poetry.dependencies]
python = "^3.10"
mkdocs = "^1.5.3"
mkdocs-material = "^9.4.6"
mkdocs-minify-plugin = "^0.7.1"
mkdocs-git-revision-date-localized-plugin = "^1.2.1"
mkdocs-glightbox = "^0.3.4"
pymdown-extensions = "^10.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
serve = "yorko_resume.serve:main"
start = "yorko_resume.main:main"

