apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-resume
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/joshyorko/yorko-resume
    targetRevision: HEAD
    path: k8s/
  destination:
    server: https://kubernetes.default.svc
    namespace: yorko-resume
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
