apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: yorko-resume
  name: yorko-resume
  namespace: yorko-resume
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: yorko-resume
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/yorko-resume-default: "true"
        io.kompose.service: yorko-resume
    spec:
      containers:
        - args:
            - poetry
            - run
            - mkdocs
            - serve
            - -a
            - 0.0.0.0:8000
          image: ghcr.io/joshyorko/yorko-resume:main
          imagePullPolicy: Always
          name: yorko-resume
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
      restartPolicy: Always
