name: Deploy MkDocs to GitHub Pages 
on:
  push:
    branches:
      - documentation-staging
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - run: pip install poetry
      - run: poetry install
      - run: poetry run mkdocs gh-deploy --force

